# Generated by Django 5.2.6 on 2026-05-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Direct WhatsApp link (e.g., https://wa.me/911234567890)'),
        ),
    ]
