# Generated by Django 5.2.6 on 2026-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pricelists/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pricelists/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
