# Generated by Django 5.2 on 2026-07-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_description'),
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['brand__name', '-created_at']},
        ),
        migrations.AddField(
            model_name='pricelist',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='brands.brand'),
        ),
    ]
