# Generated by Django 5.2.6 on 2026-06-24 08:32

from django.db import migrations


def copy_main_images_to_gallery(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductImage = apps.get_model('products', 'ProductImage')
    for product in Product.objects.all():
        if product.main_image:
            ProductImage.objects.get_or_create(
                product=product,
                image=product.main_image.name,
                defaults={'is_main': True, 'order': 0}
            )

def reverse_copy_main_images(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_main_images_to_gallery, reverse_copy_main_images),
    ]
